### ISSUE TITLE
ArduPilotManager fails when running on Desktop

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#102]
```
File "companion-docker/core/services/ardupilot_manager/flight_controller_detector/Detector.py", line 5, in <module>
    from smbus2 import SMBus
ModuleNotFoundError: No module named 'smbus2'
```

It would be good to at least catch this.

**Comment by patrickelectric** [comment]
Did you used a venv or installed the dependencies via setup.py ?
https://github.com/bluerobotics/companion-docker/blob/master/core/services/ardupilot_manager/setup.py

**Comment by rafaellehmkuhl** [comment]
Setup.py directly

**Comment by patrickelectric** [comment]
And it did not install smbus2 ? I have done a quick test here and it installed it

**Comment by rafaellehmkuhl** [comment]
Hey, I probably missed something during the setup.py install. I runned it again and it indeed installed now.
