### ISSUE TITLE
Neither Mavproxy nor MavlinkRouter are installed by default

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#104]
Companion needs at least one of them to connect to the autopilot.

**Comment by patrickelectric** [comment]
How did you installed it and how are you executing it ?

**Comment by rafaellehmkuhl** [comment]
Through ardupilot_manager's setup file.
I've assumed I could install and run it standalone.

**Comment by patrickelectric** [comment]
Companion was made to be installed by the installation script, that will install and do what is necessary to run companion.
Running services individually is not supported, however we do develop the services with such idea in mind, but extra steps may be necessary.

**Comment by patrickelectric** [comment]
This should be more clear now with #105, be free to reopen the issue
