### ISSUE TITLE
Move to Python 3.8

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#117]
Some of the features that would be available include new type hints:
- [Literal](https://docs.python.org/3/whatsnew/3.8.html#typing)
- [TypedDict](https://docs.python.org/3/whatsnew/3.8.html#typing)

**Comment by patrickelectric** [comment]
We need to check which distributions come with python 3.8

**Comment by patrickelectric** [comment]
ping @Williangalvani

**Comment by Williangalvani** [comment]
Yes, we'll need to move to another image other than buster-slim.
Maybe one of the Python ones based on buster:
https://hub.docker.com/_/python

**Comment by rafaellehmkuhl** [comment]
This is done, right? @patrickelectric @Williangalvani

**Comment by patrickelectric** [comment]
We are in Python 3.9 now, done in #161
