### ISSUE TITLE
Camera disconnect-reconnect handling is not working

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/companion-docker#145]
When I unplug and replug the camera, the video does not come back till reboot.

**Comment by jaxxzer** [comment]
There is no output in the shell indicating the conditions changed

**Comment by patrickelectric** [comment]
> There is no output in the shell indicating the conditions changed

The information is there but not accessible for now, it'll be done soon.

I'm investigating the issue, but it appears that gstreamer is not providing events related to the pipeline when the camera disconnects, will check if there a way for gstreamer to check for that periodically for us.
