### ISSUE TITLE
Mavlink logging system

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#154]
Currently we do have logging enable by default on MavlinkRouter (`--log <dir>`) and MAVProxy (`--state-basedir=<dir>`), although I think it's not correctly implemented on MAVProxy (should be `--logfile=LOGFILE`).

We also have the possibility for File endpoints on the Endpoint implementation, although neither MavlinkRouter nor MAVProxy allow them.

What do we want in the end?

I was thinking about the following possibility:
- Keep the default logging at /tmp
- Allow for File endpoints on all interfaces, and stream/log the data on the desired file. This would be a feature implemented on top of the two router interfaces, effectively adding functionality to them.

What do you guys think? @jaxxzer @Williangalvani @patrickelectric

**Comment by patrickelectric** [comment]
@rafaellehmkuhl can you point the PR that fixes the issue ?

**Comment by rafaellehmkuhl** [comment]
This issue was intended to track the File endpoint behaviour, but this was removed on #152
