### ISSUE TITLE
Navigator ardusub does not come back after mavlink reboot command

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/companion-docker#170]
In the past we would restart the binary after the process exits: https://github.com/bluerobotics/companion-docker/blob/8bfb13a55f3941b6986ea3c0b4d7982dd19bc6bd/core/services/ardupilot_manager/main.py#L32

**Comment by patrickelectric** [comment]
ref: https://github.com/ArduPilot/ardupilot/issues/17572
