### ISSUE TITLE
Do we need CORS? -> We need CORS!

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#196]
Is there some use case were CORS is needed? 
Accessing a service on the Companion through another machine works without it?

**Comment by Williangalvani** [comment]
I think the issue right now is that as we don't have something like nginx serving everythhing under the same port. And different ports could be considered different domains, causing CORS issues, but this needs to be checked.

**Comment by rafaellehmkuhl** [comment]
We need CORS to fetch data from one service to another (e.g.: the main frontend fetching data from the services).

**Comment by patrickelectric** [comment]
I believe that is time to have a web server for companion so, @rafaellehmkuhl please push the frontend template to a repository when possible

**Comment by rafaellehmkuhl** [comment]
Will. I'm currently solving some typescript warnings, but will upload an image so you guys can take a feel.

**Comment by rafaellehmkuhl** [comment]
Regarding have some service like nginx putting everybody under the same hostname, this won't solve for the need of CORS, as they will continue to be hosted on different ports (thus being considered different origins).

**Comment by patrickelectric** [comment]
nginx Will redirect all cors related communication to a path

**Comment by rafaellehmkuhl** [comment]
@Williangalvani remembered that we can put all services under the same URL, just different paths, so this should solve the problem of local services.

**Comment by patrickelectric** [comment]
They can if they want, I don't see a problem with that

**Comment by Williangalvani** [comment]
Cors can be enable on nginx itself. There's no need to implement it for each individual server

**Comment by rafaellehmkuhl** [comment]
> Cors can be enable on nginx itself. There's no need to implement it for each individual server

Yes. Best solution.

**Comment by rafaellehmkuhl** [comment]
Fixed by #351
