### ISSUE TITLE
Helper does not find docs available under different API versions

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#204]
Currently it's hard-coded to look for "/v1.0/docs". We should make it found more versions available (e.g.: v1.1, v2.1, etc) and maybe return the more recent one.

**Comment by patrickelectric** [comment]
Should be fixed by: https://github.com/DeanWay/fastapi-versioning/pull/45
or: https://github.com/DeanWay/fastapi-versioning/pull/44

**Comment by rafaellehmkuhl** [comment]
@patrickelectric This is fixed, right?

**Comment by patrickelectric** [comment]
Yes, was done in #219 and the PRs in the previous comment.
