### ISSUE TITLE
Cable-guy swagger is missing documentation for endpoints in /docs

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#205]
Found in: d1183dc
![image](https://user-images.githubusercontent.com/1215497/116707913-920dad80-a9a5-11eb-9773-32a3b3ff53a7.png)

It's missing /ethernet

**Comment by rafaellehmkuhl** [comment]
It's not. Check under /v1.0/docs.

/docs alone shows only non-API endpoints (index, for example) and the available docs.

**Comment by patrickelectric** [comment]
`/docs` should not exist since is not useful, this is also what the helper is pointing to. We should remove `/docs` or redirect it to `/docs/latest/`

**Comment by rafaellehmkuhl** [comment]
It's useful since it points out the available versions of the API, and also the available non-versioned endpoints (like index).

On the other hand, helper should point to the latest API version, I agree.

**Comment by rafaellehmkuhl** [comment]
[This issue](#204 ) is is aimed to solve that.

**Comment by patrickelectric** [comment]
@rafaellehmkuhl can you fix your hyperlink ?

**Comment by rafaellehmkuhl** [comment]
Fixed
