### ISSUE TITLE
Core: Add general web application 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#207]
May 27: 
Since I'll be working half time/period, I'll explain what I did and what was the problems that I found while doing a introspection about the technologies and libraries for our webpage idea. 
- Typescript is a must thing and it improves the software architecture and development.
- We are aiming to have an API in our frontend that we'll be used to abstract mostly of the services and provide an easy way for us to manage companion and also the user experience without the pain to maintain it as the original companion. 
- Integrate services and also 3rd party web pages as a plugin-like system for companion, the object behind this:
    - The same powerful and easy abstraction in the frontend can be used for the plugin system (services and 3rd party web pages)
    - Provides easy and generic integration 
    - Allows the same look and feel (since css and components will be used from the main webpage)
    - Better integration compared to others alternatives besides vue components.
    - But there are problems:
        - I was unable to make it work with typescript, but it was a great experience using javascript: [vue-sfc-loader](https://github.com/FranckFreiburger/vue3-sfc-loader)

About UI libraries, right now we are using Metro UI, that have a great ecosystem and component library but is there is no vue support, resulting in a hard time for developers to maintain and create a great UI for our clients.
An alternative for it was searched and Quasar was the best alternative for now, it supports both Vue 3 (the next release) and full typescript support. The only problem with Quasar is that `quasar dev` takes long times to rebuild the page in development mode and has a poor integration with developmental pages that are already open when a restart is necessary in the command, since it fails to catch some typescript components. 

References:
https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds
https://forum.vuejs.org/t/what-is-the-compiler-included-build/13239

**Comment by rafaellehmkuhl** [comment]
You mean the frontend you're working on or another thing?

**Comment by patrickelectric** [comment]
> frontend you're working

yes

**Comment by Williangalvani** [comment]
This is interesting:
https://innovation.enova.com/building-an-embeddable-micro-frontend-with-vue-js/
(I'll edit this post with new stuff I find)

**Comment by patrickelectric** [comment]
From a quick discussion between our technological investigation, sadly we found not valid alternative to create what we want to have in our final version with microservice/plugin-like system.

We agreed with the following solution:
- Create a single project for the frontend
- The project will be a monolithic project
    - This will result for now in a bit of duplicated code, since a good part of the actual development pages will be common code.
    - But this allow us to to move to a webcomponent solution or a runtime vue component compiler without much pain, since the first has a big development and maintenance cost and the second is not technological possible with typescript for now. But as said, both can be accomplished since a good part of the code will exist in the monolithic frontend. 
- We are going to use bootstrap
    - It's a popular and common UI framework and we have in house experience with @Williangalvani and @rafaellehmkuhl 
- As a consequence of using bootstrap we'll need to use vue2
    - Vue3 is not fully supported under bootstrap, for more information: https://github.com/bootstrap-vue/bootstrap-vue/issues/5196
    - Vue2 should not be a problem since Vue3 update should be a no pain process, @rafaellehmkuhl said that he can handle it without any trouble for us.
