### ISSUE TITLE
Allow connection to hidden wifi network

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#238]
Maybe a button "Connect to hidden network".

**Comment by rafaellehmkuhl** [comment]
@patrickelectric do you know if a "hidden network" does not show up on the scan, or if it shows up but with a null SSID?

**Comment by patrickelectric** [comment]
I am almost sure that it appears with an empty SSID

**Comment by rafaellehmkuhl** [comment]
If that's the case, cool, this is covered by #244.
My neighborhood has one of these (network with null SSID) and it's  showing up and converting the SSID to [HIDDEN_SSID].

**Comment by patrickelectric** [comment]
Ok, but is it possible to connect with it ? That's what the issue is about.

**Comment by rafaellehmkuhl** [comment]
> Ok, but is it possible to connect with it ? That's what the issue is about.

Don't know because I don't have the password :rofl: 

Will open one here and test.

**Comment by rafaellehmkuhl** [comment]
Just tested here and indeed if some network has "Wireless SSID Broadcast" disabled, the network appears in the scan, but the SSID comes as `null`.

Yet to test connection.
