### ISSUE TITLE
Default endpoint for Ground Station communication is not supported by MavlinkRouter

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#240]
The "GCS Link" endpoint is of the type "udpin", which is not supported by MavlinkRouter.

Easy solution is to use a type that is supported by all MavProxy, MavlinkRouter and QGroundControl.

**Comment by Williangalvani** [comment]
![image](https://user-images.githubusercontent.com/4013804/118671780-22cdf100-b7ce-11eb-85d4-d03c8ba32c44.png)

This works well for the rov while we don't have a udpbcast option

**Comment by rafaellehmkuhl** [comment]
> ![image](https://user-images.githubusercontent.com/4013804/118671780-22cdf100-b7ce-11eb-85d4-d03c8ba32c44.png)
> 
> This works well for the rov while we don't have a udpbcast option

only problem there is that we need to know the IP of the GCS machine on runtime, right?

**Comment by Williangalvani** [comment]
yes. but while we work on it, I see no issue in using 192.168.2.1. This is the IP where the current companion assumes the GCS is.

**Comment by patrickelectric** [comment]
I agree with it, but I believe that is more an QGC issue than ours since it should find the ROV over the network, and not hardcoding stuff and having a GCS as a server.

**Comment by rafaellehmkuhl** [comment]
Agree with both on that.

What do you think should be our approach today?

Have in mind MavlinkRouter is our default router on core today.

**Comment by patrickelectric** [comment]
I would recommend to hardcode the IP as suggested.
