### ISSUE TITLE
core: ardupilot-manager: Shows no endpoint in new image

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#254]
![image](https://user-images.githubusercontent.com/1215497/118864416-597f3680-b8b6-11eb-824e-18dfc57e927e.png)

**Comment by rafaellehmkuhl** [comment]
Duplicate of #240

**Comment by patrickelectric** [comment]
Default endpoint != of QGC supported endpoint as we have discussed

**Comment by patrickelectric** [comment]
Related to #240 and #255
