### ISSUE TITLE
No information regarding how to build and run a custom docker image on Companion on wiki

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#262]
It would be cool to have some info on the wiki explaining how to build a custom image and run it, in a way version-chooser picks it and allows the user/dev to test it.

**Comment by patrickelectric** [comment]
Are you taking about this ? https://github.com/bluerobotics/companion-docker/wiki/Development

**Comment by rafaellehmkuhl** [comment]
Not exactly. I'm referring to build it inside a raspberry pi itself, not cross-compiling.

**Comment by rafaellehmkuhl** [comment]
Solved by @Williangalvani on the last wiki update.
