### ISSUE TITLE
Pip is randomly and silently failing

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/companion-docker#277]
This leaves us with a successfully-built image with failing services due to missing dependencies.

Probably related issues during build:
![photo5866048483448960782](https://user-images.githubusercontent.com/4013804/119561415-81b9da00-bd7b-11eb-9271-29bf0209619b.jpg)
![photo5866048483448960778](https://user-images.githubusercontent.com/4013804/119561422-83839d80-bd7b-11eb-82bd-f3f2c3989a6f.jpg)

**Comment by patrickelectric** [comment]
@Williangalvani just to make sure #277 does not fix that ?

**Comment by Williangalvani** [comment]
> @Williangalvani just to make sure #277 does not fix that ?

well. I'm not 100% sure. But let's close this and we can re-open it if it shows up again.
