### ISSUE TITLE
core: ardupilot-manager: Allow updating firmware with custom URL

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#376]
Allow the user to update his board with a custom firmware directly from a URL

**Comment by patrickelectric** [comment]
We should also allow the user to update the firmware running from a file and not only from a url address.

**Comment by rafaellehmkuhl** [comment]
> We should also allow the user to update the firmware running from a file and not only from an url address.

Yes! The custom-file option is already coming with today's PR. This custom-URL option was something @jaxxzer mentioned it would be cool to have, so I'm opening the issue so I don't forget about it.

**Comment by rafaellehmkuhl** [comment]
Solved on #378
