### ISSUE TITLE
core: ardupilot-manager: Fails to create udpserver endpoint

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#389]
How to replicate:
- Create udp server  to 0.0.0.0 14550
- It'll not work
- Create an udp client with another ip address, udp server now works

**Comment by rafaellehmkuhl** [comment]
Was able to reproduce. Will check.

**Comment by rafaellehmkuhl** [comment]
I was able to reproduce it in another way:

1. Create UDP Server endpoint at 0.0.0.0 14332 ---> It stops other original UDP Server (0.0.0.0 14550)
2. Create UDP Server endpoint at 0.0.0.0 143333 ---> Eveybody works again

**Comment by patrickelectric** [comment]
Reference #481

**Comment by rafaellehmkuhl** [comment]
Just tested with QGC and it's working properly, without need to create extra endpoints after the first one.
