### ISSUE TITLE
Version Chooser frontend keeps loading when there's no internet connection on the network

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#390]
As we move to the main frontend, the old one does not need to be fixed. Opening the issue so we track this change for the new one.

DAYS_TO_DEVELOP:2

**Comment by Williangalvani** [comment]
it does load here, but it takes 18s to do so. My guess is that the backend is taking a long time to time out.

**Comment by rafaellehmkuhl** [comment]
From what I can remember I've waited more than that and it didn't stop, but will double check.

**Comment by patrickelectric** [comment]
It would be nice to have a "no internet connection" message, a offline game would also be nice :t-rex: :eyes:

**Comment by rafaellehmkuhl** [comment]
Just tested here 

> it does load here, but it takes 18s to do so. My guess is that the backend is taking a long time to time out.

Just tested here and after 1 minute the `companion-core` request hadn't completed yet.

**Comment by rafaellehmkuhl** [comment]
I would add a suggestion of behavior here: if there's no internet connection, show the local images and the current image, and allow regular behavior with them.

**Comment by rafaellehmkuhl** [comment]
Fixed with #770

**Comment by rafaellehmkuhl** [comment]
Fixed on #770
