### ISSUE TITLE
frontend: Add network webpage

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#403]
- [ ] Network configuration
    - [ ] DHCP client
    - [ ] DHCP server
        - [ ] Show list of clients
    - [ ] Static IP 
- [ ] Speed test from browser (Future)
- [ ] Speed test from the internet provider (Future)
- [ ] Wifi connection
- [ ] IP information about network interfaces
- [ ] Current speed for each network interface (Future)

**Comment by rafaellehmkuhl** [comment]
For Beta I would remove the three speed tests. 
Although important for the final release, they don't seem to match the Beta goal ("perform basic functionality").

**Comment by rafaellehmkuhl** [comment]
I split this issue into three other (#448, #443 and #442) dedicated to each matter (wifi, ethernet and speed).
Closing this one.
