### ISSUE TITLE
Notification system is crazy when ROV turns off or is not available on the network

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#413]
![2021-08-13_21-25](https://user-images.githubusercontent.com/1215497/129430410-e84a872f-4362-4e55-aae8-279c846109a1.png)

**Comment by rafaellehmkuhl** [comment]
Hfuehfuehduhe

Yeah

This is happening because different requests are intercalated.

Maybe we should do like you've said before and just merge all equal notifications.

**Comment by patrickelectric** [comment]
We may want also to have a high level notification message saying that communication may be lost. 
Maybe something on the header ?

**Comment by rafaellehmkuhl** [comment]
I was just thinking about that.

If there's no communication, all the other messages do not make sense, so we could add a COMM_LOST message, that, when present, suppress the push of any other messages.

**Comment by patrickelectric** [comment]
That sounds like a good approach

**Comment by rafaellehmkuhl** [comment]
> We may want also to have a high level notification message saying that communication may be lost.
> Maybe something on the header ?

Didn't get the header idea, though. What do you mean?

**Comment by patrickelectric** [comment]
In main webpage we could have something that indicates that the connection with the ROV was lost besides a high priority notification on the notification trail, like:
![image](https://user-images.githubusercontent.com/1215497/129458324-4b166853-bb5e-4ca4-9bcb-b66760d8a957.png)

**Comment by rafaellehmkuhl** [comment]
Cool! Will do!

**Comment by patrickelectric** [comment]
- Done in https://github.com/bluerobotics/companion-docker/pull/608
