### ISSUE TITLE
core: frontend: Update wifi icon in the header bar with wifi quality of signal

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#434]
![2021-08-27_07-52](https://user-images.githubusercontent.com/1215497/131123305-8c80be5c-612f-4f2e-b27c-133d562de60b.png)
![2021-08-27_07-53](https://user-images.githubusercontent.com/1215497/131123358-e1c7e238-0af4-4221-a2f1-7a51639e8160.png)

**Comment by rafaellehmkuhl** [comment]
Solved on #506
