### ISSUE TITLE
frontend: Add Wifi manager

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/companion-docker#442]
- [ ]  Show wifi adapter IP
- [ ] Allow connection to available networks
  - [ ] Unprotected
  - [ ] Protected
  - [ ] Hiden
- [ ] Allow disconnection from current network

**Comment by patrickelectric** [comment]
@rafaellehmkuhl this was already merged, no ?

**Comment by patrickelectric** [comment]
As reference: #391

**Comment by rafaellehmkuhl** [comment]
> @rafaellehmkuhl this was already merged, no ?

Yep
