### ISSUE TITLE
Bootstrap: download status is flooding the screen.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/companion-docker#50]
It needs to be updated to print the output of the low_level_api nicely [here](https://github.com/bluerobotics/companion-docker/blob/master/bootstrap/bootstrap/bootstrap.py#L77)
![image](https://user-images.githubusercontent.com/4013804/93795493-d1a23900-fc0f-11ea-8468-22208286fffe.png)

**Comment by patrickelectric** [comment]
Fix #52
