### ISSUE TITLE
Linux: firmware validation should check if it is able to run

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/companion-docker#538]
I ran into this issue after updating gcc:
![image](https://user-images.githubusercontent.com/4013804/136877606-e5087d29-fff7-442e-874e-8a7a97e255f3.png)
[ardusub.zip](https://github.com/bluerobotics/companion-docker/files/7326326/ardusub.zip)

**Comment by rafaellehmkuhl** [comment]
@Williangalvani just to confirm, were you able to upload a valid one after that?

**Comment by Williangalvani** [comment]
> @Williangalvani just to confirm, were you able to upload a valid one after that?

yes
