### ISSUE TITLE
core: frontend: camera-manager: video items are not sorted correctly

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#543]
The order appears to change, we should filter by device ID or by name, maybe device ID and name, or udev information if available. 
![image](https://user-images.githubusercontent.com/1215497/136965242-9fbf66b2-9db6-4407-900d-1733b5f37ba3.png)

DAYS_TO_DEVELOP: 0.2

**Comment by rafaellehmkuhl** [comment]
Oh, ok. I read filter and though you were having problem with duplicates.

**Comment by rafaellehmkuhl** [comment]
@patrickelectric you can put a "DAYS_TO_DEVELOP: 0.2" here.
