### ISSUE TITLE
frontend: version-chooser: Filter versions by newer

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#593]
![image](https://user-images.githubusercontent.com/1215497/137544214-8df4abe0-85b5-4855-8b79-882bda32ba9f.png)

We should filter and get the new versions on the top
It appears that only affects remote versions

**Comment by Williangalvani** [comment]
can someone replicate this?

**Comment by rafaellehmkuhl** [comment]
No. They look correct here.

**Comment by patrickelectric** [comment]
Also unable here. will close now until further update.
