### ISSUE TITLE
frontend: Log Browser loading forever

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#619]
![image](https://user-images.githubusercontent.com/1215497/139113586-603f52bf-944d-4dc7-b6aa-3fed2c878628.png)
![image](https://user-images.githubusercontent.com/1215497/139113659-1d89e045-d146-4741-878c-64b85c530cc7.png)

**Comment by rafaellehmkuhl** [comment]
Fixed with #669
