### ISSUE TITLE
core: ArduPilot-Manager: Trying to upload firmware twice in a row breaks the interface.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/companion-docker#633]
![image](https://user-images.githubusercontent.com/4013804/139447738-e0158b9c-856c-40c4-a2ad-096c0b294037.png)

**Comment by Williangalvani** [comment]
steps:
build an ardusub binary, flash it.
change the code and build it again.
try to flash the new firmware from the interface.

**Comment by rafaellehmkuhl** [comment]
From what we discussed on the call, there's no request on the backend, so this is probably the browser looking at the new file and saying to the file:

"YOU SON OF AN ROV! ARE YOU TRYING TO MAKE ME THINK YOURE SOMEONE ELSE? I ALREADY KNOW `ardusub` AND IS NOT YOU!"

Probably some protection against injection that we need to bypass.

**Comment by rafaellehmkuhl** [comment]
Apparently it's [a chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=364002).

More info [here](https://www.py4u.net/discuss/334268).
