### ISSUE TITLE
core: wifi: Different access points with the same name are apearing individually on manager

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/companion-docker#664]
BR California has 15 wifi access points and that makes the list really weird for the user point of view
We should filter that somehow or maybe created a collapsed list ? 
Is there a way to check if there are the same access points ?

**Comment by rafaellehmkuhl** [comment]
If they have the same name, they are considered to be the same acess point on most wifi managers. 
It's just a matter of filtering out for the one which is connected or the one with the best signal.
